@DocumentClassificationService_HostAddress = http://localhost:5172

# Testar a Classificação de Documento
POST {{DocumentClassificationService_HostAddress}}/api/v1/classify
Content-Type: application/json
Accept: application/json

{
  "documentId": "123",
  "documentType": "invoice",
  "content": "texto extraído ou base64",
  "sourceVertical": "retail"
}