@DocumentClassificationService_HostAddress = http://localhost:5172

# Testar a Classificação de Documento
POST {{DocumentClassificationService_HostAddress}}/api/v1/classify
Content-Type: application/json
Accept: application/json

{
  "documentId": "123",
  "documentType": "invoice",
  "content": "Y2xvdGh0aWxsYWR2ZW50dXJlYWRqZWN0aXZlZHJlc3Njb3VsZG1pbGVldmVyeXRoaW4",
  "sourceVertical": "Varejo"
}